"use client"
import {useEffect,useMemo,useState} from "react"
import PageHeader from "@/components/common/PageHeader"
type E={id:string;title:string;description:string;startAt:string;endAt:string|null;allDay:boolean;color:string}
const monthNames=["January","February","March","April","May","June","July","August","September","October","November","December"]
function key(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const colors=["#f9a8d4","#fb7185","#f97316","#facc15","#4ade80","#22d3ee","#60a5fa","#a78bfa","#c084fc","#f472b6"]
export default function CalendarPage(){
 const [date,setDate]=useState(new Date());const [events,setEvents]=useState<E[]>([]);const [open,setOpen]=useState(false);const [form,setForm]=useState({title:"",description:"",date:key(new Date()),time:"12:00",allDay:false,color:"#f9a8d4"})
 async function load(){const r=await fetch("/api/calendar",{cache:"no-store"});if(r.ok)setEvents((await r.json()).events||[])}
 useEffect(()=>{void load()},[])
 const days=useMemo(()=>{const y=date.getFullYear(),m=date.getMonth(),first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());return Array.from({length:42},(_,i)=>{const d=new Date(start);d.setDate(start.getDate()+i);return d})},[date])
 const monthEvents=events.filter(e=>{const d=new Date(e.startAt);return d.getFullYear()===date.getFullYear()&&d.getMonth()===date.getMonth()})
 async function add(){if(!form.title.trim())return;const start=new Date(form.date+"T"+(form.allDay?"00:00":form.time));const r=await fetch("/api/calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:form.title,description:form.description,startAt:start.toISOString(),allDay:form.allDay,color:form.color})});if(r.ok){setOpen(false);setDate(new Date(start.getFullYear(),start.getMonth(),1));setForm({...form,title:"",description:""});void load()}}
 return <main className="min-h-screen bg-gradient-to-br from-purple-950 via-black to-pink-950 p-4 text-white"><div className="mx-auto max-w-5xl"><PageHeader title="📅 Shared Calendar" backHref="/home"/><div className="mt-4 rounded-3xl border border-white/10 bg-white/5 p-4 backdrop-blur-xl">
 <div className="flex items-center justify-between"><button onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()-1,1))} className="rounded-xl bg-white/10 px-4 py-2">‹</button><h2 className="text-xl font-bold">{monthNames[date.getMonth()]} {date.getFullYear()}</h2><button onClick={()=>setDate(new Date(date.getFullYear(),date.getMonth()+1,1))} className="rounded-xl bg-white/10 px-4 py-2">›</button></div>
 <div className="mt-4 grid grid-cols-7 text-center text-xs text-white/45">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x} className="p-2">{x}</div>)}</div>
 <div className="grid grid-cols-7 overflow-hidden rounded-2xl border border-white/10">{days.map(d=>{const es=events.filter(e=>key(new Date(e.startAt))===key(d));const muted=d.getMonth()!==date.getMonth();return <div key={key(d)} style={!muted&&es[0]?{backgroundColor:es[0].color+"22",boxShadow:"inset 0 0 0 1px "+es[0].color+"66"}:undefined} className={"min-h-24 border-b border-r border-white/10 p-2 "+(muted?"opacity-35":"")+(es[0]?" transition":"")}><div className={"text-xs font-semibold "+(es[0]?"":"text-white/90")}>{d.getDate()}</div><div className="mt-1 space-y-1">{es.slice(0,3).map(e=><div key={e.id} style={{backgroundColor:e.color+"44",borderLeft:"3px solid "+e.color}} className="truncate rounded px-1.5 py-1 text-[10px] font-medium">{e.title}</div>)}</div></div>})}</div>
 <button onClick={()=>{setForm({...form,date:key(new Date())});setOpen(true)}} className="mt-4 w-full rounded-2xl bg-pink-500/25 py-3 font-semibold">＋ Add event</button>
 <div className="mt-5 space-y-2">{monthEvents.map(e=><div key={e.id} className="rounded-2xl bg-black/20 p-3"><div className="flex items-start justify-between gap-3"><div><div className="font-semibold">{e.title}</div><div className="text-xs text-white/45">{new Date(e.startAt).toLocaleString()}</div>{e.description&&<div className="mt-1 text-sm text-white/65">{e.description}</div>}</div><button onClick={async()=>{await fetch("/api/calendar",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"delete",id:e.id})});void load()}} className="rounded-lg bg-white/10 px-2 py-1 text-xs">Delete</button></div></div>)}</div>
 </div>
 {open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-md rounded-3xl bg-zinc-950 p-5"><h3 className="text-xl font-bold">Add event</h3><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Event title" className="mt-4 w-full rounded-xl bg-white/10 p-3 outline-none"/><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Description" className="mt-2 w-full rounded-xl bg-white/10 p-3 outline-none"/><div className="mt-2 grid grid-cols-2 gap-2"><input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})} className="rounded-xl bg-white/10 p-3"/><input type="time" value={form.time} onChange={e=>setForm({...form,time:e.target.value})} disabled={form.allDay} className="rounded-xl bg-white/10 p-3 disabled:opacity-40"/></div><div className="mt-4"><div className="mb-2 text-sm text-white/60">Event colour</div><div className="flex flex-wrap gap-2">{colors.map(color=><button key={color} type="button" onClick={()=>setForm({...form,color})} aria-label={"Choose "+color} className={"h-8 w-8 rounded-full border-2 transition "+(form.color===color?"scale-110 border-white":"border-transparent")} style={{backgroundColor:color}}/>)}<label className="relative h-8 w-8 overflow-hidden rounded-full border-2 border-white/20 bg-gradient-to-br from-red-400 via-green-400 to-blue-400" title="Custom colour"><input type="color" value={form.color} onChange={e=>setForm({...form,color:e.target.value})} className="absolute inset-0 h-full w-full cursor-pointer opacity-0"/></label></div></div><label className="mt-3 flex items-center gap-2 text-sm"><input type="checkbox" checked={form.allDay} onChange={e=>setForm({...form,allDay:e.target.checked})}/> All day</label><div className="mt-5 flex gap-2"><button onClick={()=>setOpen(false)} className="flex-1 rounded-xl bg-white/10 py-3">Cancel</button><button onClick={()=>void add()} className="flex-1 rounded-xl bg-pink-500/30 py-3 font-semibold">Add</button></div></div></div>}
 </div></main>
}
