"use client"
import {Suspense,useEffect,useRef,useState} from "react"
import {useRouter,useSearchParams} from "next/navigation"
import VideoList from "@/components/watch/youtube/VideoList"
declare global{interface Window{YT:any;onYouTubeIframeAPIReady?:()=>void}}
function Page(){const p=useSearchParams();const router=useRouter();const roomId=p.get("roomId")||"";const [room,setRoom]=useState<any>();const [results,setResults]=useState<any[]>([]);const [query,setQuery]=useState("");const player=useRef<any>(null);const suppress=useRef(false);const version=useRef(-1)
useEffect(()=>{if(!room?.videoId)return;const make=()=>{if(!window.YT?.Player||player.current)return;player.current=new window.YT.Player("wt-player",{videoId:room.videoId,playerVars:{playsinline:1,enablejsapi:1},events:{onReady:()=>{}}})};if(window.YT?.Player)make();else{window.onYouTubeIframeAPIReady=make;const s=document.createElement("script");s.src="https://www.youtube.com/iframe_api";document.body.appendChild(s)}return()=>{player.current?.destroy?.();player.current=null}},[room?.videoId])
useEffect(()=>{if(!roomId)return;let stop=false;async function poll(){const r=await fetch("/api/youtube/watch-together?roomId="+encodeURIComponent(roomId),{cache:"no-store"});if(!r.ok)return;const d=await r.json();if(stop||!d.room)return;setRoom(d.room);if(d.room.version!==version.current){version.current=d.room.version;if(player.current){suppress.current=true;const current=player.current.getVideoData?.().video_id;if(current!==d.room.videoId)player.current.loadVideoById(d.room.videoId,d.room.position);else player.current.seekTo(d.room.position,true);d.room.playing?player.current.playVideo():player.current.pauseVideo();player.current.setVolume(d.room.volume);player.current.setPlaybackRate(d.room.playbackRate);setTimeout(()=>suppress.current=false,300)}}}poll();const t=setInterval(poll,1000);return()=>{stop=true;clearInterval(t)}},[roomId])
async function sync(){if(!player.current||suppress.current)return;await fetch("/api/youtube/watch-together",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"sync",roomId,videoId:player.current.getVideoData().video_id,position:player.current.getCurrentTime(),playing:player.current.getPlayerState()===1,volume:player.current.getVolume(),playbackRate:player.current.getPlaybackRate()})})}
useEffect(()=>{if(!room||!player.current)return;const t=setInterval(()=>void sync(),2500);return()=>clearInterval(t)},[room?.id])
async function search(){if(!query.trim())return;const r=await fetch("/api/youtube/search?q="+encodeURIComponent(query));const d=await r.json();setResults(Array.isArray(d)?d:[])}
async function choose(id:string){if(!player.current)return;player.current.loadVideoById(id,0);setTimeout(()=>void sync(),500)}
async function invite(){if(!player.current)return;const r=await fetch("/api/youtube/watch-together",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"create-invite",videoId:player.current.getVideoData?.().video_id||room?.videoId,position:player.current.getCurrentTime?.()||0,playing:player.current.getPlayerState?.()===1,volume:player.current.getVolume?.()||100,playbackRate:player.current.getPlaybackRate?.()||1})});if(r.ok)alert("Watch Together invitation sent ❤️")}
async function leave(){await fetch("/api/youtube/watch-together",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"leave",roomId}));router.push("/watch/youtube")}
if(!room)return <main className="min-h-screen bg-black text-white flex items-center justify-center">Joining Watch Together…</main>
return <main className="min-h-screen bg-gradient-to-br from-purple-950 via-black to-pink-950 p-4 text-white"><div className="mx-auto max-w-2xl"><div className="flex items-center justify-between"><h1 className="text-xl font-bold">🫂 Watch Together</h1><button onClick={leave} className="rounded-xl bg-white/10 px-4 py-2">🚪 Leave</button></div>{!room.otherPresent&&<div className="mt-3 rounded-xl bg-white/10 p-3 text-sm">{room.otherNickname} left the room.</div>}<div id="wt-player" className="mt-4 aspect-video w-full overflow-hidden rounded-3xl bg-black"/><button onClick={()=>void invite()} className="mt-3 w-full rounded-2xl bg-white/10 py-3">👥 Invite to Watch Together</button><div className="mt-4"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==="Enter"&&void search()} placeholder="🔍 Search another video" className="w-full rounded-2xl bg-white/10 px-4 py-3 outline-none"/>{results.length>0&&<div className="mt-3"><VideoList videos={results} onWatchTogether={()=>void invite()} onSelect={choose}/></div>}</div></div></main>}
export default function WatchTogetherPage(){return <Suspense fallback={<main className="min-h-screen flex items-center justify-center">Loading…</main>}><Page/></Suspense>}
