ALTER TABLE "NoteBook" ADD COLUMN "backgroundImage" TEXT;

CREATE TABLE "WatchRoom" ("id" TEXT NOT NULL,"homeId" TEXT NOT NULL,"videoId" TEXT NOT NULL,"position" DOUBLE PRECISION NOT NULL DEFAULT 0,"playing" BOOLEAN NOT NULL DEFAULT false,"volume" INTEGER NOT NULL DEFAULT 100,"playbackRate" DOUBLE PRECISION NOT NULL DEFAULT 1,"version" INTEGER NOT NULL DEFAULT 0,"lastActionAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WatchRoom_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WatchRoomMember" ("id" TEXT NOT NULL,"roomId" TEXT NOT NULL,"userId" TEXT NOT NULL,"joinedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastSeenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"leftAt" TIMESTAMP(3),CONSTRAINT "WatchRoomMember_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WatchInvite" ("id" TEXT NOT NULL,"homeId" TEXT NOT NULL,"roomId" TEXT NOT NULL,"senderId" TEXT NOT NULL,"recipientId" TEXT NOT NULL,"videoId" TEXT NOT NULL,"position" DOUBLE PRECISION NOT NULL DEFAULT 0,"expiresAt" TIMESTAMP(3) NOT NULL,"status" TEXT NOT NULL DEFAULT 'PENDING',"customMessage" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"respondedAt" TIMESTAMP(3),CONSTRAINT "WatchInvite_pkey" PRIMARY KEY ("id"));
CREATE INDEX "WatchRoom_homeId_idx" ON "WatchRoom"("homeId");
CREATE UNIQUE INDEX "WatchRoomMember_roomId_userId_key" ON "WatchRoomMember"("roomId","userId");
CREATE INDEX "WatchInvite_recipientId_status_idx" ON "WatchInvite"("recipientId","status");
CREATE INDEX "WatchInvite_expiresAt_idx" ON "WatchInvite"("expiresAt");
ALTER TABLE "WatchRoom" ADD CONSTRAINT "WatchRoom_homeId_fkey" FOREIGN KEY ("homeId") REFERENCES "Home"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchRoomMember" ADD CONSTRAINT "WatchRoomMember_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "WatchRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchRoomMember" ADD CONSTRAINT "WatchRoomMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchInvite" ADD CONSTRAINT "WatchInvite_homeId_fkey" FOREIGN KEY ("homeId") REFERENCES "Home"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchInvite" ADD CONSTRAINT "WatchInvite_roomId_fkey" FOREIGN KEY ("roomId") REFERENCES "WatchRoom"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchInvite" ADD CONSTRAINT "WatchInvite_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WatchInvite" ADD CONSTRAINT "WatchInvite_recipientId_fkey" FOREIGN KEY ("recipientId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "WatchSetting" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"expiryMinutes" INTEGER NOT NULL DEFAULT 10,CONSTRAINT "WatchSetting_pkey" PRIMARY KEY ("id")); CREATE UNIQUE INDEX "WatchSetting_userId_key" ON "WatchSetting"("userId"); ALTER TABLE "WatchSetting" ADD CONSTRAINT "WatchSetting_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;